### PR TITLE
refactor: simplify entities classes

### PR DESCRIPTION
**Pull request by DulongSang**
Simplified some entity classes.
NOTE:
deleted QRBucks class, move the functionalities to DriveRequest class.

### CODE REVIEW

**Comment by DulongSang** [comment]
I have resolved the conflict, and I want to mention some **important changes** for this update:

1. All entity classes are simplified to be only responsible for saving data, which means each class only has its only data fields (private attributes) and getters, setters for each attribute (required by firebase).
2. For the `User` class, added a new attribute of float type, `balance`, that stores the user's balance.
3. For the `DriveRequest` class, the instance only has attributes of riderID and driverID, which are Strings (the instance used to reference a Rider and a Driver as its attribute.)
4. Removed the `QRBucks` class, since its functionality can be merged into `DriveRequest` class.

**Comment by sharyar** [comment]
Hey Dulong
The name is not redundant. It refers to the user's real name. 
The username is the unique username each user creates for themselves.

**Comment by DulongSang** [comment]
> Hey Dulong
> The name is not redundant. It refers to the user's real name.
> The username is the unique username each user creates for themselves.

OK, got it. I thought the username is just the same as the userID. I will re-add the `name` attribute.

**Comment by sharyar** [comment]
> > Hey Dulong
> > The name is not redundant. It refers to the user's real name.
> > The username is the unique username each user creates for themselves.
> 
> OK, got it. I thought the username is just the same as the userID. I will re-add the `name` attribute.

Thanks!

**Comment by DulongSang** [comment]
I have re-added the `name` attribute.

**Pull request merged**
